language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: z6azlrvxzpj0dzJx2HZyKMG8/mlwwUcIN/lQfZnZfLWoKDtWUQz6NckfOtiHRYGkZMiUVQarNAmwAc+7cGDj6f0ewFUHYuh78tEdfkcmaD81ffalyhBIv92ADN3l4eEEEhpxCwsyT+3Ljm3D1TaGR8qEV9XOpu/V1+GNh/6UePClik4SS0A0Dk+x4b+f9+Q51YXdsaWRXRngg9wbCnZWjhnNdypfbtz4bQscCaLz6li6T/XxlvHEn7Iu1AeXPRfixpSWmD8jXyQ44pefV4N2xi/Pmt9XmSdc5oLk/DpBkmqSjkaeAjBl9/JSgaiY9BpXnk7XyLqW9MozVD16xq/5nUsFeqIEskTRxqcVhTXnvkCc0GjWH7MzCgtB81/foUscm/IZ/Z46rK1IoYloyRhmtZVM2Sv0sMk6KOZkR3C7dsk5BogqarV2tflChlnH0eTgEVEUTgJCKVBS0IfdAYeCOZARMHodTlcg4VSInEI1iyQRPx9DFnG0xbs0AQ9AVtjLbx4hDijyELHBS7elvyz0PauLC+cvzfdFDfbpgYCT3K0OqFWZ7BjUIeVm8lhp91kI4EcZfGLjJND+nW3sDeTvK/qmD4koEqyLRwZF8Sez9VEiSgWaUeJx323Pya67qtwBDnUbIXqUOHg8Q/fU6s3gWO3mESQXXs7ZjVZqkCca2xE=
  app: secret-string
  on:
    repo: DillonStreator/secret-text
